### ISSUE TITLE
Pytorch

### ISSUE THREAD

**Issue by chungyau97** [lidq92/SFA#1]
I can't really find a pytorch version of this code.
Can anyone share with me? @lidq92

**Comment by lidq92** [comment]
@chungyau97 This work is implemented using MATLAB and Caffe. 
Following README.md, you can easily use it to reproduce the work.

Of course, It is very easy to implement using Python and PyTorch.
You are very welcome to follow the paper and this repository to implement by yourself.
You may refer to some Python codes of [VSFA](https://github.com/lidq92/VSFA), the extension to the VQA domain. You also need to implement PLSR with `PLSRegression` (`from sklearn.cross_decomposition import PLSRegression`).
But we should note that the pre-trained model files between PyTorch and Caffe are different, and the performance may show a little variation.

When I am free, I may spend some time to reimplement this method with Python and PyTorch.

**Comment by lidq92** [comment]
@chungyau97 Now you can have a look at [SFA-pytorch](https://github.com/lidq92/SFA/tree/master/SFA-pytorch)
