### ISSUE TITLE
how to great data.mat

### ISSUE THREAD

**Issue by skk-k** [lidq92/SFA#14]
Hello, I would like to consult with you,
How is your data.mat folder built, What does each variable mean, and what does it contain? Especially how your index data is created? I want to test the new datasets with your model, but I don t know how to create the datasets.mat (like KonIQ.mat) document. Hope for your help.
Thank you very much for your help!
Thank you.

**Comment by lidq92** [comment]
You may want to learn from [this file](https://github.com/lidq92/VSFA/blob/master/data/data_info_maker.m)

**Comment by skk-k** [comment]
Excuse me, I see a data file "/media/ldq/Research/Data/KoNViD-1k/KoNViD_1k_attributes.csv" in the link. How is the specific content created?

**Comment by lidq92** [comment]
It's nothing. It is just the (raw) subjective data providedby the owner. There is a similar csv file in KonIQ. 

The mat files in the repo just re-organized the data file provided by the datasets' owners.
