### ISSUE TITLE
The link of "my sharing on BaiduNetDisk" is gone!!

### ISSUE THREAD

**Issue by chencuber** [lidq92/SFA#15]
Hi, it seems downloading  these database is difficult, can you update your database link? Thanks!

**Comment by lidq92** [comment]
You can download the [KonIQ-10k](http://database.mmsp-kn.de/koniq-10k-database.html) and [CLIVE](https://live.ece.utexas.edu/research/ChallengeDB/index.html) datasets from this [alternative link](https://pan.baidu.com/s/1FtHstHT0eTA1cmZ-vNiZ_Q) with password 9pwl. 

If you need other datasets, please try to download them from the original links provided by the owners (I tried to re-share the files but failed. Maybe some files are forbidden to be shared in BaiduNetDisk) .
