### ISSUE TITLE
about SFA_pytorch how to use adaptive layer selection procedure

### ISSUE THREAD

**Issue by Benica924** [lidq92/SFA#18]
hello,about SFA_pytorch how to use adaptive layer selection procedure, on the readme.md 'Add adaptive layer selection procedure used in the journal version'.Is it me who needs to rewrite this file? Or can the author provide the appropriate version code?

**Comment by lidq92** [comment]
@Benica924 I just provided the base version of SFA-pytorch for reference. It should be easy for people to add adaptive layer selection procedure on top of the code by referring to the official MATLAB code. Currently, I have no time to do the `TODOs` in [README](https://github.com/lidq92/SFA/blob/master/SFA-pytorch/README.md). For benchmarking SFA, please use the MATLAB version or the reported results from the MATLAB version.
