### ISSUE TITLE
Writing an Application layer

### ISSUE THREAD

**Issue by aayusharora** [lidq92/SFA#3]
Hi,
The Pytorch code works and I am able to get some values. I have two questions:
1. Is their way to test the blurriness of a single image rather than preparing test dataset at run time with indexes ( i.e currently done by reading the matlab file )
2. How can I train the model again? Can you please elaborate, how to utilise .Mat files better?

**Comment by lidq92** [comment]
@aayusharora 

1. You can refer to the [`Demo.m`](https://github.com/lidq92/SFA/blob/master/Demo.m) and the `test_demo.py` in my other repos, such as [VSFA](https://github.com/lidq92/VSFA/blob/master/test_demo.py), [CNNIQA](https://github.com/lidq92/CNNIQA/blob/master/test_demo.py), and [WaDIQaM](https://github.com/lidq92/WaDIQaM/blob/master/test.py). 

Currently, I do not have free time to add a `test_demo.py`. It is quite easy to do that, and you can do it by yourself.

2. You can prepare your own `.mat` file for your own dataset, you can refer to [`data_info_maker.m`](https://github.com/lidq92/VSFA/blob/master/data/data_info_maker.m) to get more details.

For the training, you can refer to [`SFA.py`](https://github.com/lidq92/SFA/blob/master/SFA-pytorch/SFA.py) for more details.

Finally, when I am free, I will improve this repo to make things clearer.

**Comment by aayusharora** [comment]
Thanks @lidq92 for your help.
