### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by zhushuyun** [lidq92/SFA#4]
你好，能提供一下python语言的demo吗？

**Comment by lidq92** [comment]
@zhushuyun  我没用过Python接口的Caffe (我现在不用Caffe了，所以不会专门抽时间去写一个Python接口的Caffe demo的)。
你有需求的话，可以参考着原始的MATLAB+Caffe的代码和我最近新提供的Python+PyTorch的代码改写一下下就行。（印象中RankIQA原作者用的好像是Python接口的Caffe，你也可以参考一下）

祝好

**Comment by zhushuyun** [comment]
好的，谢谢，顺便问一下，您的网络输出表示的是分数吗？值的大小和图像质量是怎样的关系？

________________________________
zhushuyun@navinfo.com

**Comment by lidq92** [comment]
@zhushuyun 输出是一个数值。

如果是用我提供的在LIVE训练好的模型，那么值越大质量越差（因为LIVE主观分数是DMOS）

如果你用一个新的数据集重新训练，那么预测的值大小和图像质量的好坏关系和这个新数据集的主观分数大小与图像质量的好坏关系一致。

虽然可以直接类似demo那样调用测试，但是如果你想用这个模型需要自己有一定理解。
比如举个例子：在LIVE 高斯模糊图像上训练的模型拿去测随手拍的一张模糊的图像，那就不一定有很好的指示作用。

**Comment by zhushuyun** [comment]
好的，非常感谢！！！


祝好

________________________________
zhushuyun@navinfo.com
