### ISSUE TITLE
关于pytorch程序

### ISSUE THREAD

**Issue by upupbo** [lidq92/SFA#6]
请问Which Has Better Visual Quality: The Clear Blue Sky or a Blurry Animal?论文的pytorch程序什么时候会公布，谢谢。

**Comment by lidq92** [comment]
@upupbo 目前很忙，没有具体公布的计划。请使用我提供的原始Caffe+MATLAB版本。

这个repo下也提供了会议版本的Pytorch实现，在我的github里还提供了一些其他IQA repos。
你如果有改进需求的话可以自己参考着我的项目进行修改即可。
