### ISSUE TITLE
Will the `PLCC be a negative number` during the `cross database` train and test?

### ISSUE THREAD

**Issue by SuperBruceJia** [lidq92/SFA#9]
Dear Dingquan,

Your work is awesome! It's truly great!!

As for the notation here:

```
Note for cross dataset evaluation
The reported Spearman correlation (SROCC) is multiplied by -1 when the training and testing datasets have different forms of subjective scores, i.e., one is MOS and the other is DMOS. This is to make sure that the prediction monotonicity is better when SROCC is closer to 1.
```

So, for cross-validation, if two databases used MOS and DMOS respectively, the SRCC will be a negative number. What about the PLCC? Will the PLCC be a negative number too? 

I'm looking forward to your early reply and have a nice day!

Best,

Shuyue

**Comment by lidq92** [comment]
If there is no nonlinear mapping, the PLCC should be also multiplied by -1 when the training and testing datasets have different forms of subjective scores, i.e., one is MOS and the other is DMOS.

However, in the cross-dataset evaluation setting, a nonlinear mapping is fitted (in the above situation it should be a decrease function). In this sense, the PLCC (after nonlinear mapping) does not need to be multiplied by -1.

**Comment by SuperBruceJia** [comment]
> If there is no nonlinear mapping, the PLCC should be also multiplied by -1 when the training and testing datasets have different forms of subjective scores, i.e., one is MOS and the other is DMOS.
> 
> However, in the cross-dataset evaluation setting, a nonlinear mapping is fitted (in the above situation it should be a decrease function). In this sense, the PLCC (after nonlinear mapping) does not need to be multiplied by -1.

Thanks a lot Dingquan, u are truly an extraordinary man!!!! Really awesome!!!!
